version: 2

jobs:
    "python-3.6":
        docker:
            - image: circleci/python:3.6-stretch-node-browsers

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "tests/requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Generations tests
                command: |
                    . venv/bin/activate
                    pytest tests --drive Chrome
                when: always


workflows:
    version: 2
    build:
        jobs:
            - "python-3.6"
